- .projen/deps.json
- .projenrc.js
- package.json
- src/NextjsLambda.ts
- yarn.lock
> Depend on deployment of config before rewriting

- src/NextjsAssetsDeployment.ts
- src/NextjsBuild.ts
- src/NextjsLambda.ts
> fix: Skip static file deployment if no files

- assets/lambda/NextJsHandler.ts
More info: https://github.com/dougmoscrop/serverless-http/issues/227
> fix: Request body was not being passed to NextJS

- .projen/deps.json
- .projenrc.js
- package.json
- src/NextjsBuild.ts
- yarn.lock
Shaves 17MB off the standalone function bundle
> Strip sharp dep from bundle

- src/Nextjs.ts
> fix: Fix hosted zone lookup

- assets/lambda/NextJsHandler.ts
The server config had improper and missing fields for middleware to properly work.
> fix: broken middleware

- API.md
- README.md
- assets/lambda/NextJsHandler.ts
- assets/lambda@edge/LambdaOriginRequest.ts
- src/Nextjs.ts
- src/NextjsAssetsDeployment.ts
- src/NextjsBuild.ts
- src/NextjsLambda.ts
Add an easy option to specify how long the **browser** should cache static files for
This can be very long as the files are immutable, as in the filename changes if the content changes so effectively they can be cached forever
> feat: Cache-control max-age

- src/NextjsLambda.ts
Fixes #48 
The `NextjsS3EnvRewriter` and its lambda function: `S3EnvRewriter` performs a noop if there's nothing to replace.
The Construct creates a bucket and saves and empty "{}" to `next-env.json` in S3.
The lambda function reads the file from S3 and "bails" if it's empty.
This will slightly speed up deployment time.
> chore: skip S3EnvRewriter when the replacement is empty

- src/NextjsBase.ts
- src/NextjsBuild.ts
Fixes https://github.com/jetbridge/cdk-nextjs/issues/76
> feat: choose between npm and yarn as package manager for NextJS build

- API.md
- src/NextjsBase.ts
- src/NextjsBuild.ts
- src/NextjsDistribution.ts
Fixes https://github.com/jetbridge/cdk-nextjs/issues/78
also fixes some eslint issues that were introduced by my previous PR 👻
> feat: customize name of edge function stack id

- .projen/deps.json
- .projenrc.js
- API.md
- package.json
- src/Nextjs.ts
- src/NextjsAssetsDeployment.ts
- src/NextjsS3EnvRewriter.ts
- src/index.ts
- yarn.lock
Fixes #84
For some reason the `addDependency` bit doesn't work with CDK 2.50, I had to update it and it worked
> fix: Wait to deploy server function until rewriting is complete

- src/NextjsBuild.ts
Fixes #93 
Currently, deploying on Windows fails because the zip file generation command is written for Linux / MacOS.
I added the command to spawn powershell and generate zip with `Compress-Archive` command. This should work in any modern Windows environment.
> fix: Support windows by replacing zip command.

- src/utils/create-archive.ts
> fix: windows archive with powershell

- .projen/deps.json
- .projenrc.ts
- API.md
- examples/app-router/src/stack.ts
- package.json
- src/utils/common-lambda-props.ts
- yarn.lock
Update Lambda functions to Node.js 20
> feat: update lambda to Node.js 20

- API.md
- docs/major-changes.md
- src/Nextjs.ts
- src/NextjsBase.ts
- src/NextjsBuild.ts
- src/NextjsDistribution.ts
- src/NextjsImage.ts
- src/NextjsRevalidation.ts
- src/NextjsServer.ts
- src/index.ts
> fix: remove NextjsBaseProps

- .projen/deps.json
- .projenrc.ts
- .vscode/settings.json
- API.md
- examples/app-pages-router/package.json
- examples/app-pages-router/pnpm-lock.yaml
- examples/app-router/package.json
- examples/app-router/pnpm-lock.yaml
- examples/high-security/package.json
- examples/high-security/pnpm-lock.yaml
- examples/high-security/src/stack.ts
- examples/pages-router/package.json
- examples/pages-router/pnpm-lock.yaml
- package.json
- src/NextjsBucketDeployment.ts
- src/NextjsServer.ts
- src/NextjsStaticAssets.ts
- src/lambdas/nextjs-bucket-deployment.ts
> fix: 403 assets on deployment

- src/NextjsDistribution.ts
Update edge lambda from node 18 to 20
> feat: update edge lambda from node 18 to 20

- API.md
- src/NextjsDistribution.ts
- src/generated-structs/OptionalNextjsBucketDeploymentProps.ts
- src/generated-structs/OptionalNextjsDistributionProps.ts
- src/generated-structs/OptionalNextjsDomainProps.ts
- src/generated-structs/OptionalNextjsImageProps.ts
- src/generated-structs/OptionalNextjsInvalidationProps.ts
- src/generated-structs/OptionalNextjsRevalidationProps.ts
- src/generated-structs/OptionalNextjsServerProps.ts
- src/generated-structs/OptionalNextjsStaticAssetsProps.ts
> feat: security headers by default

- src/lambdas/nextjs-bucket-deployment.ts
When pruning old S3 objects, we ran into an issue where more than 1000 keys are attempted to be deleted at once which results in an error.
From AWS docs "The request can contain a list of up to 1000 keys that you want to delete."
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/delete-objects.html
This PR chunks the delete by batches of 1000 at a time to avoid the error.
> fix: delete from s3 in chunks

- src/NextjsDomain.ts
> fix: spread dns record overrides into props

- src/Nextjs.ts
> fix: NextjsDomain overrides

- .projen/deps.json
- .projenrc.ts
- API.md
- package.json
- src/generated-structs/OptionalARecordProps.ts
- src/generated-structs/OptionalAaaaRecordProps.ts
- src/generated-structs/OptionalCertificateProps.ts
- src/generated-structs/OptionalCloudFrontFunctionProps.ts
- src/generated-structs/OptionalDistributionProps.ts
- src/generated-structs/OptionalEdgeFunctionProps.ts
- src/generated-structs/OptionalFunctionProps.ts
- src/generated-structs/OptionalProviderProps.ts
- yarn.lock
> fix: upgrade cdk 2.131.0

- .github/workflows/release.yml
- .projen/tasks.json
- .projenrc.ts
- package.json
> fix: Major Version Release

- src/Nextjs.ts
> fix: Add environment to NextjsServer

- examples/README.md
> fix: examples readme

- .projenrc.ts
- package.json
> fix: Fix faulty Node engine version in package.json
