jetbridge/cdk-nextjs

- src/Nextjs.ts
If you look at the CloudFront Distribution, the precedence ordering of `_next/*` is above `_next/image*`.  I believe that means it'll never match `_next/image`. Please correct me if I'm wrong.
> fix: fix precendence ordering of image path

- README.md
This problem and configuration is not exclusive to monorepos, which may lead to confusion and error for users who aren't using monorepos - as they will skip this important step.
> fix: update quickstart doc to address non monorepo

- assets/lambda@edge/LambdaOriginRequest.ts
- src/Nextjs.ts
Fixes a bug where we weren't forwarding all headers to the default behavior. Basically not all headers were available to `getServerSideProps` functions. Now they should be. 
This didn't work before because the Host header would be wrong for the lambda function URL origin but we now have a Lambda@Edge function to fix up the Host header.
> fix: Forward all headers to SSR pages

- src/NextjsBuild.ts
Fixes #34 
There may be some usecase/scenario where there are no public folders (someone in discord had this setup)
Wasn't sure if we should add this validation in the `listDirectory` function but it's only being used in 2 places right now.
> fix: prevent crash if nextjs app does not contain public folder

- .projen/deps.json
- .projenrc.js
- API.md
- README.md
- assets/lambda/ImageOptimization.ts
- assets/lambda/ImageOptimization/index.ts
- assets/lambda/NextJsHandler.ts
- assets/lambda/utils.ts
- package.json
- src/ImageOptimizationLambda.ts
- src/Nextjs.ts
- src/NextjsAssetsDeployment.ts
- src/NextjsBuild.ts
- src/NextjsDistribution.ts
- src/NextjsLambda.ts
- src/NextjsLayer.ts
- src/index.ts
- yarn.lock
fixes: #24 
Adds support for Image Optimization. I was unable to get the standalone optimization for some reason, but if someone can get that working that would be preferable over adding this feature.
- Supports images hosted on S3 or external images (don't forget to config domains in next.config.js)
Feedback appreciated.
TODO: Add documentation
Usage:
```
const site = new NextjsSst(stack, 'Web', {
app,
...
imageOptimizationBucket: bucket, // Optional, if not provided, it will use the assets bucket, NOTE: each deployment will clear resources not in the `/public` folder
...
})
```
```
// Add trusted domains in next.config.js
images: {
remotePatterns: [
{
protocol: 'https',
hostname: '**.example.com',
},
],
},
```
Upload some images in the assets or the bucket you provided, eg: …
> feat: image optimization

- README.md
Improves documentation. Make supported NextJs versions more clear. Earlier the text was **12.3.0+** , which could've been misinterpreted as Next v12 only ( min 12.3.0 ). The change provides the context that Next 13 is also supported.
> chore: Make supported NextJs version more clear

- src/NextjsDistribution.ts
Server response should have higher priority than S3 assets since most assets are cached at bucket level policy.
> chore: move server ahead of s3 group

- src/ImageOptimizationLambda.ts
Currently, the `cp` command will generate the `required-server-files.json` at the root of the project (annoying).
The `commandHook's` `inputDir` is the root of the project, so we can just use `nextBuild` to grab the files... no need to read the file data.
> chore: simplify required server files copy

- .projen/deps.json
- .projenrc.js
- package.json
- src/ImageOptimizationLambda.ts
- src/NextjsDistribution.ts
- src/NextjsLambda.ts
- src/NextjsLayer.ts
- src/NextjsS3EnvRewriter.ts
- src/constants.ts
- yarn.lock
If not using super latest aws-cdk-lib then you can't deploy since the node_18_x runtime isn't defined
> fix: Node16 runtime

- assets/lambda/ImageOptimization/placeholder.ts
- src/ImageOptimizationLambda.ts
We can skip some image fn bundling stuff if we're just building a placeholder (`sst start`)
```
cp: cannot stat '/home/cyber/dev/packages/frontend/.next/standalone/packages/frontend/.next/required-server-files.json': No such file or directory
```
> fix: Skip image fn bundling if placeholder

- API.md
- src/BundleFunction.ts
- src/NextjsBase.ts
- src/NextjsBuild.ts
- src/NextjsLambda.ts
Trying to make it clearer what's going on with the path relative to the output tracing root inside the standalone output directory.
Helps with the error about missing `required-server-files.json` (at least for me, please try it)
Fixes #61 
Please try this and let me know if it works for your setup!
> fix: Output paths

- .projen/deps.json
- .projen/tasks.json
- .projenrc.js
- README.md
- package.json
- yarn.lock
Still not great
Open to suggestions for making esbuild not bundled with cdk-nextjs in #36
> chore: be explicit about esbuild version and lock it to specific version

- src/Nextjs.ts
Fixes #84 (again 😅)
PR https://github.com/jetbridge/cdk-nextjs/pull/86 introduced a better way to ensure deploy dependencies between the Lambda server function and the Env Rewriter.
However after this change, if you don't pass anything to `props.environment`, your `rewriter` will be falsey and you will not get any server => S3 dependencies added due to the if condition.
This change makes sure you will either get a dependency on the rewriter if you have one, else just the S3 deployment itself.
> fix: Make sure lambda always has a dependency on S3 assets

- API.md
- src/NextjsDistribution.ts
- src/index.ts
AWS only allows 20 Origin request policies per AWS account:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-policies
As each unique environment deploys 3 different OAPs, you will run into the limit after deploying more than 6 instances of this package.
This change allows you to pass your own OAPs to allow for both more customization as well as the ability to share the same OAP between multiple deployments (ex `OriginRequestPolicy.fromOriginRequestPolicyId()`)
> feat: Allow all origin request policies to be passed as props

- src/NextjsDistribution.ts
Fixes #100 
It appears that we can pass in multiple domain names to the cloudfront distribution
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudfront.Distribution.html#:~:text=g.%2C%20example.com/).-,domainNames%3F,Alternative%20domain%20names%20for%20this%20distribution.,-enableIpv6%3F
Modifies `buildDistributionDomainNames` to combine the list of `alternateNames` with the `customDomain` if they exist
> fix: Allow alternate domain names in the distribution

- src/NextjsDistribution.ts
Add 'rsc', 'next-router-prefetch', 'next-router-state-tree' to lambda cache policy
Fixes #106
> feat: add 'rsc', 'next-router-prefetch', 'next-router-state-tree' to lambda cache policy

- src/NextjsBase.ts
- src/NextjsBuild.ts
Currently, `cdk-nextjs` is not compatible with the latest v2+ version of `open-next`. Work is being done to update the project to be compatible, but for now we'll make sure new users coming to `cdk-nextjs` for the first time are to deploy a working Next.js site.
see: https://github.com/jetbridge/cdk-nextjs/issues/126
Fixes #
> fix: pin major version of open-next to 1

- .projenrc.js
- API.md
- src/ImageOptimizationLambda.ts
- src/Nextjs.ts
- src/NextjsBase.ts
- src/NextjsBuild.ts
- src/NextjsDistribution.ts
- src/NextjsLambda.ts
- src/NextjsRevalidation.ts
- src/NextjsRevaluation.ts
- src/NextjsS3EnvRewriter.ts
- src/constants.ts
- src/index.ts
See: https://github.com/jetbridge/cdk-nextjs/issues/119
Updates the server handler to include cache bucket configuration, **which is likely not correct as I'm just using the static asset bucket temporarily**. I need to look at how SST does this and what the spirit of this should be, e.g. if a separate bucket would be more appropriate, a folder, etc.
This also adds the ISR handling logic. I haven't actually tested this yet (am not 100% sure how to).
**This is a WIP**.
Fixes #119 
1. ~~Confirm if we should make a new bucket for cache or use an existing bucket~~
2. ~~Confirm permissions appropriate for this bucket between nextjs server and the bucket~~
3. Confirm if ISR feature is working and what else may be needed
4. ~~Make sure I didn't break anything along the way~~
5. I'd like to add …
> fix: Initial support for open-next v2 and ISR

- .gitignore
- .projenrc.ts
- API.md
- README.md
- examples/README.md
- examples/multiple-sites/.gitignore
- examples/multiple-sites/README.md
- examples/multiple-sites/cdk.json
- examples/multiple-sites/package.json
- examples/multiple-sites/pnpm-lock.yaml
- examples/multiple-sites/src/app.ts
- examples/multiple-sites/src/stack.ts
- examples/multiple-sites/tsconfig.json
- src/Nextjs.ts
- src/NextjsBase.ts
- src/NextjsDistribution.ts
- src/NextjsStaticAssets.ts
- Support to `next.js` `basePath` on Distribution
- Support multiple Next.js sites on same Distribution;
- Support passing existing/custom Distribution;
> feat: basePath and allow multiple next.js sites on same distribution (passing custom distribution)

- .projen/deps.json
- .projenrc.ts
- API.md
- package.json
- src/NextjsBase.ts
- src/NextjsBuild.ts
- src/NextjsImage.ts
- src/NextjsRevalidation.ts
- src/NextjsServer.ts
- src/constants.ts
- yarn.lock
This diff adds the DynamoDB table and supporting data provider function to support Next.js path and tag revalition. This feature is supported by `open-next` (read more about it here: https://open-next.js.org/inner_workings/isr#tags) and is inspired by https://github.com/sst/sst/compare/v2.27.0...v2.28.0
The changes include
* Adding a new DynamoDB table which stores time stamps, tags, and paths for revalidation consideration
* Adds a function (`dynamodb-provider`) which populates the DynamoDB table on deployment with the initial set of tags / paths / timestamps generated in the Next.js build phase
* **Bumps `aws-cdk-lib` to 2.95.1**, matching the SST version for access to `DynamoDB.TableV2`
* Adds a simple description to the "primary" server handler
A bit more info:
I did this because SST …
> feat: add dynamodb table and provider for tag and path revalidation

- API.md
- src/NextjsDistribution.ts
Fixes #118 
Problem: Not being able to update the static response headers policy can lead to quota issues, if you want to deploy feature branches of your app. This change should make it possible to reuse the same policy for all feature branches.
> fix: #118 allow to customize the static response headers policy

- src/NextjsStaticAssets.ts
This pull request closes #160.
Currently there is a check in `NextjsBuild.ts` https://github.com/jetbridge/cdk-nextjs/blob/15deeb7cf6a6f8963d796f92526d78dbfe7070f3/src/NextjsBuild.ts#L87 if the deploy is being made with the `--exclusively` flag and then the build is skipped.
This check is not present when creating S3 assets, so it will try to copy asset files from the `.open-next` folder, which does not exist if the build has been skipped. https://github.com/jetbridge/cdk-nextjs/blob/15deeb7cf6a6f8963d796f92526d78dbfe7070f3/src/NextjsStaticAssets.ts#L66
This causes any deployment to fail with the following error:
```
Warning: /home/runner/work/<app-name>/<app-name>/clients/website/.open-next does not exist.
Warning: /home/runner/work/<app-name>/<app-name>/clients/website/.open-next/assets …
```
> fix: skip asset bundling if cdk deploy is made with --exclusively flag

- src/NextjsDistribution.ts
Addresses the issue brought up in this discussion post: https://github.com/jetbridge/cdk-nextjs/discussions/163
TLDR: optional custom CloudFront props were not being passed to the create distribution function.
> fix: connect cf override props with distribution creation

- API.md
- src/NextjsDistribution.ts
Fixes #136
Also, refactor security headers to take advantage of `ResponseHeadersPolicyProps.securityHeadersBehavior`.
> feat: add cache-control on all origins

- src/NextjsDistribution.ts
Fixes #189
AllowList accept-encoding headerBehaviour is not compatible with enableAcceptEncodingGzip: true.
My recommendation is to remove accept-encoding from allowList headerBehaviour as default. And the final user can amend as they wish. But like this, the default options will be functional.
Fixes #
> fix: 400 Bad request when creating CachePolicy on the Distribution.

- src/lambdas/nextjs-bucket-deployment.ts
When uploading a site with hundreds of static assets, the custom lambda resource that uploads to S3 will error out with `Error: EMFILE: too many open files`.
This is due to a read stream being opened for every static upload concurrently.
This PR batches the uploads into more manageable chunk sizes so there isn't an limitless number of file pointers opened at once.
> fix: upload to s3 in chunks

- docs/code-deployment-flow.md
- src/NextjsBuild.ts
Fixes https://github.com/jetbridge/cdk-nextjs/issues/175
it works :)
> fix: destroy with no bundling

- API.md
- src/NextjsDistribution.ts
> feat: use existing distribution policies when provided

- API.md
- src/NextjsServer.ts
> fix: server overrides

- src/NextjsDistribution.ts
The value of a cookie would never change how an image is rendered, so cookies should not be included in the image cache policy.
> fix: ignore cookies in image cache policy

- src/lambdas/sign-fn-url.test.ts
- src/lambdas/sign-fn-url.ts
Fixes # https://github.com/jetbridge/cdk-nextjs/issues/214
> fix: re-map authorization header when using secured function urls

- .projen/deps.json
- .projen/tasks.json
- .projenrc.ts
- package.json
- src/lambdas/nextjs-bucket-deployment.ts
- yarn.lock
We started frequently facing this error when uploading S3 assets
`RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.`
After some research, it seems like using the Upload constructor from @aws-sdk/lib-storage has more fault tolerance and better retry logic than the usual S3 PutObjectCommand.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-lib-storage/
We have been running this change in production for a few weeks now and haven't had the error happen once since, so it seems to fix the issue.
> fix: Use S3 `Upload` function instead of `PutObjectCommand`

- API.md
- src/NextjsBucketDeployment.ts
- src/NextjsStaticAssets.ts
- src/generated-structs/OptionalNextjsBucketDeploymentProps.ts
> fix: Change prune default to false to fix 404s

- API.md
- src/Nextjs.ts
- src/NextjsBuild.ts
- src/NextjsDistribution.ts
- src/generated-structs/OptionalNextjsBuildProps.ts
- src/generated-structs/OptionalNextjsDistributionProps.ts
Adds an optional parameter `streaming: true` to allow deploying Next with Lambda response streaming.
Most of the work is [already handed](https://open-next.js.org/v2/inner_workings/streaming) by `open-next` by passing the `--streaming` argument. We just need to also set the Lambda function URL invoke mode to `RESPONSE_STREAM`.
> feat: add support for lambda response streaming

- .projenrc.ts
- API.md
- src/NextjsDistribution.ts
- src/generated-structs/OptionalCloudFrontFunctionProps.ts
- src/index.ts
Fixes #229 Allows functionAssociations to be overriden by exposing an optional `overrides.nextjsDistribution.viewerRequestFunctionProps.code` prop. Sample usage:
```ts
const cmsRedirectKvStore = new cloudfront.KeyValueStore(this, "CmsRedirectKeyValueStore");
const viewerRequestCode = `
import cf from 'cloudfront';
const kvsId = 'KEY_VALUE_STORE_ID_PLACEHOLDER';
const kvs = cf.kvs(kvsId);
async function handler(event) {
// My custom code to do canonical redirects here...
// Or my code to use kv store here...
// INJECT_CLOUDFRONT_FUNCTION_HOST_HEADER
// INJECT_CLOUDFRONT_FUNCTION_CACHE_HEADER_KEY
}
`
viewerRequestCode.replace(
'KEY_VALUE_STORE_ID_PLACEHOLDER',
cmsRedirectKvStore.keyValueStoreId,
);
const nextjs = new Nextjs(this, 'Nextjs', {
nextjsPath: './web',
overrides: { …
```
> feat: Allow functionAssociations overrides

- src/NextjsDistribution.ts
Fixes #229 bug
The regexs on the cloudfront function with missing the multi-line flag and the function was missing the return!
By default the function should now be:
```
async function handler(event) {
event.request.headers["x-forwarded-host"] = event.request.headers.host;
const getHeader = (key) => {
const header = event.request.headers[key];
if (header) {
if (header.multiValue) {
return header.multiValue.map((header) => header.value).join(",");
}
if (header.value) {
return header.value;
}
}
return "";
}
let cacheKey = "";
if (event.request.uri.startsWith("/_next/image")) {
cacheKey = getHeader("accept");
} else {
cacheKey =
getHeader("rsc") +
getHeader("next-router-prefetch") +
getHeader("next-router-state-tree") +
getHeader("next-url") +
getHeader("x-prerender-revalidate");
}
if …
```
> fix: cloudfront function regex and return request

- API.md
- src/NextjsBucketDeployment.ts
- src/generated-structs/OptionalNextjsBucketDeploymentProps.ts
- src/lambdas/nextjs-bucket-deployment.ts
- yarn.lock
This appears to be a bug in the AWS s3 SDK. The root of the issue seems to be calling upload on lib-storage rather than an issue with the implementation. Switching from promise.all to a serial implentation fixes the issue, while also increasing the queue size off the default 3.
For future improvements, I would also thing about exposing more of the uploadOptions inside the next deployment construct. Perhaps we should also give consumers the options of uploading serial vs parallel.
Next steps I will also raise this with AWS team.
Fixes #228
> fix: fix XAmzContentSHA256Mismatch

- src/NextjsDistribution.ts
- src/NextjsStaticAssets.ts
- src/generated-structs/OptionalNextjsBucketDeploymentProps.ts
**Summary:**
- Fixes the glob pattern for static files so that all files under `_next/static` are matched relative to the asset root.
- Removes a stray quote in the `staticFiles` glob.
- Ensures that only `_next/static` files receive the long-term cache-control header (`public, max-age=31536000, immutable`), while all other static assets get `public, max-age=0, must-revalidate`.
- Prepares CloudFront to use a default cache-control of 0 seconds for static assets, relying on S3 object metadata to set long-term cache only for `_next/static` files.
**Why:**
Previously, the cache-control headers for static assets were not correctly applied because the glob pattern did not match the relative paths of files in `_next/static`. This led to suboptimal caching for Next.js static assets, causing …
> fix: Ensure static asset cache-control headers are correctly applied for _next/static files
